### ISSUE TITLE
Gaze Tracking

### ISSUE THREAD

**Issue by Schizo** [mpatacchiola/deepgaze#21]
Even though this frameworks is called "deepgaze" I am still not sure, if you can do Gaze Tracking and Gaze Mapping. Would appreciate a clarification.

**Comment by mpatacchiola** [comment]
Hi

At the moment the library do not include Gaze tracking. We are working on it...
Stay tuned, Massimiliano

**Comment by Schizo** [comment]
Is there any way I can contribute? Is there a library with labeled data for training?

**Comment by mpatacchiola** [comment]
It would be great to have your contribution. Yes there are datasets with labeled images, however the gaze estimation is an hard problem because requires a good head pose estimation and a consistent pre-processing of the images. We have also other open projects at the moment: fast face detections through CNNs, emotion recognition, saliency estimation... etc  Let me know if you are interested in one of those. All the best, Massimiliano.
