### ISSUE TITLE
How to handle the installation of deepgaze errors?

### ISSUE THREAD

**Issue by qianyongsheng** [mpatacchiola/deepgaze#25]
run：
cd deepgaze
sudo python setup.py install
error：
qys@qys-GL552VW:~/deepgaze$ sudo python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/deepgaze-0.1.egg-info
Writing /usr/local/lib/python2.7/dist-packages/deepgaze-0.1.egg-info

**Comment by mpatacchiola** [comment]
Hi @qianyongsheng 

it may be that you are using an old version of the `distutils` package. Inside the main folder of deepgaze you find the file called `setup.py`. Open this file with a text editor and **remove these two lines** (line 11 and 12):

`
  package_data={'deepgaze': ['Readme.md']},
`
`
  include_package_data=True,
`

Aftet this modification save the file and run again the commands:

`cd deepgaze`
`sudo python setup.py install`

If everything is fine it should work. Let me know!

Massimiliano

**Comment by qianyongsheng** [comment]
Hi Massimiliano：

Make a new mistake according to your method.:
(tensorflow) qys@qys-GL552VW:~/deepgaze/examples$ python ex_pnp_head_pose_estimation_video.py
Traceback (most recent call last):
  File "ex_pnp_head_pose_estimation_video.py", line 17, in <module>
    from deepgaze.haar_cascade import haarCascade
ImportError: No module named deepgaze.haar_cascade
No module named deepgaze.haar_cascade.
Yongsheng Qian

**Comment by mpatacchiola** [comment]
That's really strange, it seems it cannot find the deepgaze modules.
Please try to reinstall depgaze using file tracking as follows:

`
sudo python setup.py install --record record.txt
`

Send me the content of the file `record.txt`. Which operating system are you using?

Massimiliano

**Comment by qianyongsheng** [comment]
Hi Massimiliano:

I use ubuntu 16.04 and tensorflow cpu 1.3.0.
Run sudo python setup.py install --record record.txt:

/usr/local/lib/python2.7/dist-packages/deepgaze/motion_detection.py
/usr/local/lib/python2.7/dist-packages/deepgaze/head_pose_estimation.py
/usr/local/lib/python2.7/dist-packages/deepgaze/saliency_map.py
/usr/local/lib/python2.7/dist-packages/deepgaze/color_detection.py
/usr/local/lib/python2.7/dist-packages/deepgaze/haar_cascade.py
/usr/local/lib/python2.7/dist-packages/deepgaze/__init__.py
/usr/local/lib/python2.7/dist-packages/deepgaze/face_detection.py
/usr/local/lib/python2.7/dist-packages/deepgaze/bayes_filter.py
/usr/local/lib/python2.7/dist-packages/deepgaze/mask_analysis.py
/usr/local/lib/python2.7/dist-packages/deepgaze/face_landmark_detection.py
/usr/local/lib/python2.7/dist-packages/deepgaze/color_classification.py
/usr/local/lib/python2.7/dist-packages/deepgaze/cnn_head_pose_estimator.py
/usr/local/lib/python2.7/dist-packages/deepgaze/motion_tracking.py
/usr/local/lib/python2.7/dist-packages/deepgaze/motion_detection.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze/head_pose_estimation.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze/saliency_map.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze/color_detection.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze/haar_cascade.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze/__init__.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze/face_detection.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze/bayes_filter.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze/mask_analysis.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze/face_landmark_detection.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze/color_classification.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze/cnn_head_pose_estimator.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze/motion_tracking.pyc
/usr/local/lib/python2.7/dist-packages/deepgaze-0.1.egg-info

run (tensorflow) qys@qys-GL552VW:~/deepgaze/examples$ python ex_dlib_pnp_head_pose_estimation_video.py
Traceback (most recent call last):
  File "ex_dlib_pnp_head_pose_estimation_video.py", line 18, in <module>
    from deepgaze.face_landmark_detection import faceLandmarkDetection
ImportError: No module named deepgaze.face_landmark_detection
 it cannot find the deepgaze.face_landmark_detection modules

**Comment by mpatacchiola** [comment]
Everything seems fine. You have all the modules you need and they are in the correct folders in your system. It may be possible that Python does not point to `/usr/local/lib`. Try creating a new python file with the following two lines of code inside:

`import sys`
`print '\n'.join(sys.path)`

This script should print on terminal something like this:

/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
/usr/lib/python2.7/dist-packages/ubuntu-sso-client
/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode

You should check if the path `/usr/local/lib/python2.7/dist-packages` is mentioned in the list.
Probably you will not see this path. In this case you should add it in you `.bashrc` file in the `PYTHONPATH` variable. If you do not want to mess with your system files you can try to add the two following lines of code at the  beginning of the deepgaze python example:

`import sys `
`sys.path[0] = "/usr/local/lib/python2.7/dist-packages"`

The two lines should be before you call the deepgaze modules. Here you are simply telling to look for modules in the `/usr/local/lib/python2.7/dist-packages` path.

Massimiliano

**Comment by qianyongsheng** [comment]
Hi Massimiliano:


Some examples can be run ,but there was an error:

No module named deepgaze.motion_detection.
(tensorflow) qys@qys-GL552VW:~/deepgaze/examples/ex_motion_detectors_comparison_video$ python ex_motion_detectors_comparison_video.py
Traceback (most recent call last):
  File "ex_motion_detectors_comparison_video.py", line 18, in <module>
    from deepgaze.motion_detection import DiffMotionDetector
ImportError: No module named deepgaze.motion_detection
I found that still missing the module.
Yongsheng Qian

**Comment by mpatacchiola** [comment]
Hi @qianyongsheng 

From the content of the file `record.txt` that you post before it seems that the module `motion_detection` has been correctly compiled and installed. It is strange that you can use the other modules but not this one.

There is another solution. Since the Deepgaze modules are independent you can simply take only one of those and use it in your application. Copy the file `motion_detection.py` contained in the `deepgaze` folder and move it inside the `ex_motion_detectors_comparison_video` folder. In the file  `ex_motion_detectors_comparison_video.py` you have to change these three lines:

`from deepgaze.motion_detection import DiffMotionDetector`
`from deepgaze.motion_detection import MogMotionDetector`
`from deepgaze.motion_detection import Mog2MotionDetector`

and modify them as follows:

`from motion_detection import DiffMotionDetector`
`from motion_detection import MogMotionDetector`
`from motion_detection import Mog2MotionDetector`

When you run the file you may have an ASCII problem in the file `motion_detection.py` at line 94 due to a bad character. If you have this error you can simply fix the sentence `Grimson et al's tracker` to `Grimson et al tracker`.

In this way you are calling the file directly from the example folder and you should not have any problem. Anyway this is a workaround and the problem you are gettin is not usual.

Massimiliano

**Comment by nyck33** [comment]
yes, I agree there are some issues with installation.  Here we go on try number 5...

**Comment by bensalahmara** [comment]
i'm a beginner  i want to install deepgaze 
i run the file setup.py 
but there is an error:
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
An exception has occurred, use %tb to see the full traceback.

SystemExit: usage: ipykernel_launcher.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: ipykernel_launcher.py --help [cmd1 cmd2 ...]
   or: ipykernel_launcher.py --help-commands
   or: ipykernel_launcher.py cmd --help

error: option -f not recognized
how can i handel this error
note: im using google colab 
please help me

**Comment by mpatacchiola** [comment]
Hi @bensalahmara, it seems the problem is due to the fact you are installing from colab.
I am not familiar with it, but once you have installed the [prerequisites for Deepgaze](https://github.com/mpatacchiola/deepgaze/tree/2.0#prerequisites) it is just matter of copying the `deepgaze` folder in the right place in your system. I guess that colab handle this in a specific way. 

Looking rapidly online it seems that colab is similar to a notebook, and when you install by `setup.py` you need to run it this way:

```
!setup.py install
```

According to [this stackoverflow answer](https://stackoverflow.com/questions/51342408/how-do-i-install-python-packages-in-googles-colab) using `!` you are telling the notebook cell that this line is not Python code but a command line script.

Hope this helped.

**Comment by bensalahmara** [comment]
Hi @mpatacchiola  
to install deepgaze a run this:
!git clone https://github.com/mpatacchiola/deepgaze.git  => it work good
then i run 
!cd deepgaze
!setup.py install
this give an error
/bin/bash: setup.py: command not found
how can i handle this error can you help me? 
i try this way :
!cd deepgaze
!sudo python setup.py install
=>bin/bash: line 0: cd: deepgaze: No such file or directory
python3: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by mpatacchiola** [comment]
@bensalahmara it seems there are two different problems with your commands. 

1) In the first attempt there is a problem with bash that gives you the error `/bin/bash: setup.py: command not found`. You should run the command through python by writing `python setup.py install` or `!python setup.py install` instead of directly calling `setup.py` as you did. For the installation steps, follow the instruction on [this section](https://github.com/mpatacchiola/deepgaze#installation) of deepgaze mainpage. 

2) For the second error, it looks like you are not in the correct folder. With the command `cd` you can set a folder as current directory. However, in your case it looks like there is no way to find the `deepgaze` folder. Try to use the command `ls` to check the content of the current directory and verify that it contains the folder `deepgaze`. In case you are not in the correct folder you have to move in the right path by using `cd` then run the deepgaze installation script.

**Comment by bensalahmara** [comment]
HI @mpatacchiola 
To install deepgaze i do this steps:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My\ Drive
the i clone the repository :
git clone https://github.com/mpatacchiola/deepgaze.git

then i run this to to check the content of the current directory and verify that it contains the folder deepgaze:  !ls "/content/drive/My Drive"   
=>"57460.gdoc	    Imaga		      Untitled0.ipynb
 57460.pdf	   'ion smart home (1).pdf'   Untitled1.ipynb
'Colab Notebooks'  'memoir '
 deepgaze	   'Sans titre (2).pdf'  "
then i run the deepgaze installation script.
%cd deepgaze
! python setup.py install
it give me the same error :
[Errno 2] No such file or directory: 'deepgaze'
/root
python3: can't open file 'setup.py': [Errno 2] No such file or directory
i dont know how can i handle this problem :(
can you help me ?
can you check the steps i followed

**Comment by bensalahmara** [comment]
Dear mpatacchiola

I am using your program in order to determine the head pose estimation. and
i'm facing this error while im running the ex_cnn_head_pose_estimation:
my_head_pose_estimator.load_roll_variables(os.path.realpath("../../etc/tensorflow/head_pose/roll/
cnn_cccdd_30k.tf"))
my_head_pose_estimator.load_pitch_variables(os.path.realpath("../../etc/tensorflow/head_pose/pitch/
cnn_cccdd_30k.tf"))
my_head_pose_estimator.load_yaw_variables(os.path.realpath("../../etc/tensorflow/head_pose/yaw/
cnn_cccdd_30k.tf"))
it give me this error
ValueError: [DEEPGAZE] CnnHeadPoseEstimator(load_roll_variables): the roll
file path is incorrect.

I try to delete tf and i try to add a point but doesn't work
can you help me to handle this error ?
NOTE: im using python Python 3.6.9 and tensorflow 1.14
