### ISSUE TITLE
input image to the cnn_head_pose_estimation

### ISSUE THREAD

**Issue by Zouhj** [mpatacchiola/deepgaze#26]
Hi, thank you for your works!
I am not clear that what the images are exactly processed before we input to the nets? Is it just detected square face box or some translation and scaling have been down?
I test the same face image with different size, one just square the face, another is bigger and with more background, the result yaw, pitch and roll are different. So it's important to know the pictures input to model.  
wish for your replies.

**Comment by mpatacchiola** [comment]
Hi @Zouhj 

At the low level the CNN takes as input a square image of size 64x64 pixels.
However, if you pass a larger square Deepgaze will automatically resize it to be 64x64.
Be carefull because the library does not accept rectangular images or images which are smaller than 64x64 pixels. The best performance is achieved with a subframe of the face which goes from the forehead to the chin, similarly to the faces in [this example](https://github.com/mpatacchiola/deepgaze/raw/master/doc/images/ex_cnn_head_pose_estimation_images.png).

All the best, Massimiliano

**Comment by Zouhj** [comment]
Yeah, I get it. Thank you very much!
