### ISSUE TITLE
Can i use my own new images to train the model? 

### ISSUE THREAD

**Issue by shashi19081994** [mpatacchiola/deepgaze#31]
Can i use my own new images to train the model? I am working on cnn head pose estimation. your work is excellent. I was stuck with a question that "Can i use my own new images to train the model? "  whether this deepgaze will help me so in doing? Thank you.

**Comment by mpatacchiola** [comment]
Dear @shashi19081994 

At the moment there is not a file that you can use to train the model. However there is an implementation of a trainer for aDeep MLP [here in the example folder](https://github.com/mpatacchiola/deepgaze/tree/master/examples/ex_dnn_head_pose_estimation_training). You can slightly modify this example including the model and the weights used in the Deepgaze CNN [head_pose_estimation.py](https://github.com/mpatacchiola/deepgaze/blob/master/deepgaze/head_pose_estimation.py) package. If you have familiarity with Tensorflow it should be straightforward.

Once you have the file with the correct model and weights then it is necessary to pre-process your images. In the same example folder you can find some parser used on the Prima and AFLW datasets. You should modify one of the parser in order to resize and crop your images and then store them in a pickle file, which is the format used by the trainer.

At the end of the training you need to save the Tensorflow meta-files which can be loaded in Deepgaze or in your personal model.

Best, Massimiliano
