### ISSUE TITLE
about cnn head pose and update

### ISSUE THREAD

**Issue by sunskys** [mpatacchiola/deepgaze#45]
Hello, on the cnn head pose estimation in deepgze, I found no face detection module during the test. Is the network model trained on face detection? At the same time, this project will continue to be updated for gaze estimation, thanks
and If I want to train cnn head pose estimation, the data set is made into a .pickle format like dnn?

**Comment by mpatacchiola** [comment]
Hi @sunskys 

The CNN itself does not have a face detector. In the examples you [find here](https://github.com/mpatacchiola/deepgaze/tree/master/examples/ex_cnn_head_pose_estimation_images) the faces have been cropped in advance.

However, Deepgaze does have an advanced face detector. If you give a look to [this example](https://github.com/mpatacchiola/deepgaze/blob/master/examples/ex_haar_face_detection/ex_haar_face_detection.py) you can see how to use it. If you want to use the head pose estimaor in a live streaming you should find the face and then send it to the pose estimator.

The training of the CNN can be done in different ways, the pickle format is one possibility. The code is similar to the one used for training the deep network.

Regarding the gaze estimation, unfortunately we are all busy in this moment. However, it is a major feature of the library and we want to deliver it. Stay tuned...

**Comment by sunskys** [comment]
I am very happy to receive your reply. In training CNN, if I want to train only yaw, I only need to input the clipped face picture and the corresponding yaw on it? Thank you

**Comment by mpatacchiola** [comment]
Yes correct, you need the cropped face and the yaw. The AFLW dataset already has the coordinates of the faces that you can use to crop the images.

**Comment by sunskys** [comment]
Yes, I finished the face clip based on the py script provided by the aflw dataset. I just need to make a dataset like (key:image;value:yaw)? Then go to training?
For this task of predicting yaw, I think it is a regression task, not a classification task, so I want to make a training set like VOC2012? Include pictures and category labels, or are there other considerations? Can I share dataset instances? Thank you, I'm sorry to bother you.

**Comment by mpatacchiola** [comment]
Hi @sunskys 

Yes you need to have a training dataset with image-angle pairs. The angle is a continuous value and for this reason we are dealing with a regression problem.

**Comment by sunskys** [comment]
@mpatacchiola Thank you, I will complete my training task in the next time. If I have any questions, I will ask you again. Thank you.

**Comment by sunskys** [comment]
@mpatacchiola Hello, I'm sorry to bother you. In the process of processing the aflw data set, I wanted to generate a .pickle file. I executed the "ex_aflw_parser.py" file, which needed to crop the image and "/aflw/data/label.csv", and I finished the face clipping with "aflw_example.py" provided by the aflw dataset. Will "/aflw/data/label.csv" be generated, is there a corresponding script file? Thank you, there is no other corresponding csv processing tool in the "https://lrs.icg.tugraz.at/research/aflw/downloads.php" data set.
Thank you, I look forward to your help.

**Comment by mpatacchiola** [comment]
Hi @sunskys 

There is an included file for processing the AFLW dataset also in Deepgaze. Give a look to [this folder](https://github.com/mpatacchiola/deepgaze/blob/master/examples/ex_dnn_head_pose_estimation_training/ex_prima_parser.py). In particular look to the 'main()' method. There are three steps to follow, first create the CSV, then the Pickle file, and finally use the pickle in you classifier. The pickle will contain both input images and labels.

**Comment by sunskys** [comment]
@mpatacchiola 
Hello, I know you said "ex_prima_parser.py" file, and I processed the prima data set through it. I think "ex_aflw_parser.py" is used to process aflw datasets, his input needs `label.csv',
There are the following errors:
   File ".\ex_aflw_parser.py", line 47, in <module>
     With open(label_csv_path, 'rb') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: './aflw/data/label.csv'
So, what I would like to ask is how to generate the corresponding label.csv from the sql file of the aflw data set.
Thank you, I look forward to your help.

**Comment by mpatacchiola** [comment]
You have to use the function called `create_csv()` that you can find in [this file](https://github.com/mpatacchiola/deepgaze/blob/master/examples/ex_dnn_head_pose_estimation_training/ex_prima_parser.py). You just have to uncomment the lines 376 inside the main function of that fileand the CSV will be created.

Regarding the  `create_csv()` function, first of all you have to specify where the uncompressed folder with the dataset is located. Specify an output folder and the image size (be careful to choose this size, it must be less than the dimension of the original faces). You can choose if save the image in grayscale or colours.

**Comment by sunskys** [comment]
@mpatacchiola  Hello, I'm sorry to disturb you again. I tried the "ex_prima_parser.py" file you mentioned again. It can only be used to process "Prima Head Pose Image Database". What I want to deal with is the aflw dataset, which generates the .csv file corresponding to the aflw dataset. I am very sure that "ex_prima_parser.py" cannot handle aflw datasets, so I would like to process aflw datasets through "ex_aflw_parser.py" but there is no relevant script for generating csv files. The aflw official script only completes face clipping. So can you help me provide relevant documents or ideas? Thank you!

**Comment by Ostnie** [comment]
@sunskys Where can I  download the aflw official script? I only have related pictures ，Can you give me a link ？

**Comment by sunskys** [comment]
@Ostnie Sorry, this aflw dataset has copyright restrictions, so you need to apply on the official website.
"https://www.tugraz.at/institute/icg/research/team-bischof/lrs/downloads/aflw/"

**Comment by Ostnie** [comment]
@sunskys I have applyed a few days ago ,and now I don't know where is the Label file ，I mean that where is the pose information about this dataset?
Thanks!

**Comment by sunskys** [comment]
@Ostnie There is an aflw-db.tar.gz file in the aflw dataset. All relevant information is in it. You can find out

**Comment by Ostnie** [comment]
@sunskys I see, I think it isn't difficult to get the information I want , but now I have some doubt about it's unit about facepose.txt , it is radian or degree ? I see the max value is more than 6 ,and it is too large for radian and too small for degree .

**Comment by mpatacchiola** [comment]
Hi @sunskys 

Yes you are right, by accident I pointed you to the file of the Prima dataset instead of the AFLW dataset.
However, once you get access to the AFLW dataset you should find some Python files (that I wrote) for managing the dataset. The AFLW python file creates a folder where the images are stored. The next step is to create a pickle file. This is not so complicated and the Python code for the Prima dataset can help you. Remember that the pickle format is not mandatory, you can also use numpy, this is an example of pseudo-code:

```python
images_list = list()
labels_list = list()
for image in path:
    img = cv2.imread(image_path) #Open the image with OpenCV imread()
    images_list.append(img) #Append the image in a python list
    #here you should get the label (roll, pitch, yaw)
    #here you append the label in the labels_list
#When iteration is complete store the list on disk
```

You can store the list as pickle, or you can convert it to Numpy matrix and store it using the Numpy method save().

**Comment by speculaas** [comment]
Dear @Ostnie and @mpatacchiola 
Thanks for your help!
Do you know AFLW's head pose is in radian or degree?
In AFLW paper, 4.2 Face pose estimation, there seemed no mentioning of units of the angle.

I guess it's radian? 

iPath:    aflw/data/flickr/0/image04496.jpg
oPath:    ./output/0/image04496.jpg
Roll:    -0.00231315148994
Pitch:   -0.264310628176
Yaw:     -0.484094411135

BR,
Jimmy

**Comment by speculaas** [comment]
Dear mpatacchiola,
Thanks for your help!
You mentioned input to CnnHeadEstimator need to be cropped first. 
And you mentioned ex_haar_face_detection.py is a way to crop.

But I want to ask what method did you use to crop the example images?

Did you exactly used ex_haar_face_detection.py or other methods?

![deepgaze_example 2018 0831f0543pm](https://user-images.githubusercontent.com/31201176/44907292-fcc84000-ad49-11e8-9f3d-f30d30766d7f.JPG)


I ask this because I found when testing against PRIMA and AFW, 
deepgaze's estimations on raw files are always about (pitch, yaw) = (-9.23, 8.xx~7.xx)
no matter how input's pitch and yaw changed. 

And I suspect I need to crop input correctly.

BR,
JimmyYS

**Comment by mpatacchiola** [comment]
Hi @speculaas 

For the AFLW I used the bounding boxes provided with the dataset, cropping the faces as a square instead of a rectangle. The correct cropping is a problem and it may be partially solved retraining the model with a version of the dataset where the faces are slightly shifted in a random direction.

Experimentally I found that the best results are achieved when the chin is aligned with the bottom border as you see in the images you posted. Remember that while the yaw estimation is generally quite robust, the pitch is more unstable because the AFLW does not provide a large range of poses.

If I remember well the AFLW is in radiants. You can easily check it if you sample some images and print the angle.

**Comment by speculaas** [comment]
Dear mpatacchiola,
Thanks for your help!

I check aflw_example.py again, and found just what you said:
"cropping the faces as a square instead of a rectangle"

I think I didn't recognize clearly that code was cropping square. (maybe I thought it was making sure not going outside image boundary)

I guess to integrate Deepgaze into my facenet-mtcnn (https://github.com/davidsandberg/facenet) flow, I have to re-train Deepgaze.

Now I am also looking at all possible ways to estimate head pose. 

Here are what I have came across : 
2011, AFLW
2015, AFLW2000, face alignment across large poses: a 3D solution
2017, deepgaze
2018, deep-head-pose, pytorch
2018, gitlab, openheadpose, leveraging convolutional pose machines for fast and accurate head pose estimation (but I still cannot figure out how to get code from their gitlab)


Also, after random checking by my own human vision, I found some AFLW pose data may be wrong?
But according to AFLW paper, the AFLW pose data is just coarse approximation. So think some error is to be expected.

Just being curious, regarding precision measurement, maybe iphone x is a promising way to precisely measure face angles?

BR,
JimmyYS

**Comment by mpatacchiola** [comment]
Hi @speculaas 

Yes the AFLW provides a coarse estimation because it uses a generic 3D mask to evaluate the head orientation. Unfortunately I do not think there are other datasets available at the moment.

You can tackle head pose estimation using facial landmarks if the face is at a reasonable distance from the camera. However if there are occlusions of any sort or the landmarks are not visible then the method fails most of the time. CNNs provide a solution, since they are able to deal with occlusions, low resolution images and aberrations.

**Comment by speculaas** [comment]
Dear mpatacchiola, 
Thanks for your help!

I ran ex_dnn_head_pose_estimation_training.py and found: 
the predictions for roll and yaw didn't change as training progressed:

PRED:   [-1.        0.997808  1.      ]
PRED:   [-1.         -0.10718718  1.        ]
PRED:   [-1.         -0.08675322  1.        ]
PRED:   [-1.         -0.08200257  1.        ]
PRED:   [-1.         -0.08288153  1.        ]
PRED:   [-1.         -0.10492459  1.        ]
PRED:   [-1.         -0.07921617  1.        ]
...
PRED:   [-1.         -0.09386994  1.        ]
PRED:   [-1.         -0.12356951  1.        ]
PRED:   [-1.         -0.07465103  1.        ]
PRED:   [-1.         -0.07411873  1.        ]

Do you know what might be the cause?
BR,
JimmyYS

**Comment by speculaas** [comment]
Dear mpatacchiola,
Thanks for your help!

To answer my own question as stated immediately above, 
this following line always prints the same value : 

print("PRED:   " + str(predictions[0,:]))

is because only at "validation accuracy", the verbose parameter in "accuracy()" is set to true.

BR,
Jimmy

**Comment by speculaas** [comment]
Dear mpatacchiola,
Thanks for your help!

My initial doubt is why train set not rotating through different batches, 
Then I found only validation set's status is printed.

However it still not seemed right that the predicted Euler angles of the first image in validation set not changing as training progressed. 

Have you encounter this before?
What might be wrong?

BR,
Jimmy

**Comment by mpatacchiola** [comment]
Hi @speculaas 

The line 'print("PRED: " + str(predictions[0,:]))' just print the output of the network for the first image in the batch, however this image is changing at training time meaning that the prediction should change as well.

When the network is returning always the same output, it means that the optimization got stuck in a local minima. This may be due to different factors, such as normalization of the input features, structure of the network, and hyper-parameters choice. 

I suggest you to check again that the input features have been correctly normalized and that there is not any error in the network definition. As a second step you can try to evaluate different hyper-parameters, especially the one associated with the optimizer (e.g. learning rate, momentum, etc).
