### ISSUE TITLE
pitch, yaw and roll

### ISSUE THREAD

**Issue by galihjozu** [mpatacchiola/deepgaze#55]
i think that all people try to asking you this..
is it possible if ex_pnp_head_pose_estimation_webcam.py , measure how much degree the head is moving?
let say that your head tilting 45 degree, nodding 30 degree, etc

**Comment by mpatacchiola** [comment]
Hi @galihjozu 

Yes it is definitely possible, give a look to the closed issues since it has already been discussed in the past.

**Comment by kgupta15** [comment]
@galihjozu did you get the angles of pose that you were trying to get? I want the same results but havent been able to.

**Comment by galihjozu** [comment]
@daemonslayer 
take a look at https://github.com/mpatacchiola/deepgaze/issues/3

(success, rotation_vector, translation_vector) = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=cv2.CV_ITERATIVE)
rvec_matrix = cv2.Rodrigues(rotation_vector)[0]
proj_matrix = np.hstack((rvec_matrix, translation_vector))
eulerAngles = -cv2.decomposeProjectionMatrix(proj_matrix)[6] 
yaw   = eulerAngles[1]
pitch = eulerAngles[0]
roll  = eulerAngles[2]

but the result aren't degree yet. it still string..
so can you help me more @mpatacchiola . how to change the string into degree.

**Comment by kgupta15** [comment]
@galihjozu this library also provides pose estimate with yaw, pitch and roll values. Why not use them directly? Or maybe I misunderstood and you are trying to compare opencv results to library's results?

@mpatacchiola the yaw, pitch and roll values of this library are quite different from opencv's. Do I need to do some calibration of coordinate system? Also, I need to get values such that I can place glasses on to a face. Degrees of rotation per axis would be useful so that I can use the angled render of 3d glass model. Can you please suggest how I can do that? Thanks.

**Comment by galihjozu** [comment]
do you mean like this example @daemonslayer ? ex_cnn_head_pose_estimation_images

i think that example just will run in image only, i dont think that it may run in realtime webcam.
am i wrong? is it possible to measure the degree in webcam?

i am trying to add this to the code.
http://answers.opencv.org/question/161369/retrieve-yaw-pitch-roll-from-rvec/
