### ISSUE TITLE
unable to run ex_multi_backprojection_hand_tracking_gaming.py

### ISSUE THREAD

**Issue by shashank7289** [mpatacchiola/deepgaze#67]
I was able to successfully make the installations and run this code with sudo for uinput. 
Opencv is also working fine and I can see the video feed, but after pressing 'a' to start tracking, I don't see any green dot signifying the centre of my palm.

![image](https://user-images.githubusercontent.com/6208224/52946939-4873b200-339b-11e9-8f50-469a38dfc6d9.png)

when I try print(frame_mask), I get all zeros

**Comment by mpatacchiola** [comment]
Hi @shashank7289 most probably this is due to the templates used for the calibration. 

In the folder containing the example you should find a few small images called `template_1.png`, `template_2.png`, etc. These images have been taken from my palm in different light conditions.

What you should do is to use the webcam to capture a few images of your palm (using s screen capture tool), resize those templates to be small squares and replace the current templates images.

In this way the algorithm will be calibrated on your palm and should be able to find your hand.
