### ISSUE TITLE
about the 3D_Coord of the landmarks

### ISSUE THREAD

**Issue by sunjia2015** [mpatacchiola/deepgaze#8]
Hi
Thank you for sharing the code.
Could you tell me where did you get these data? Actually, I want to find out 3D coordinates of 64 landmarks detected by dlib. 
Thank you.

**Comment by mpatacchiola** [comment]
Hi Sunjia

The 3D coords have been extrapolated from anthropometric measurements of the human head. You can find on Google a pdf called "Head-and-Face Anthropometric Survey of U.S. Respirator Users" which report some of the measurements I used. Moreover on the [wikipedia page](https://en.wikipedia.org/wiki/Human_head) you can find other values. Unfortunately is not easy to find all the coords of the 64 landmarks used in dlib, because the antropometric measurements are generally based on some specific keypoints.
