### ISSUE TITLE
Head pose from video

### ISSUE THREAD

**Issue by sarmadm** [mpatacchiola/deepgaze#9]
Hi

Can I use video file for head pose estimation ?

**Comment by mpatacchiola** [comment]
Hi sarmadm

Yes you can use a video for head pose estimation. In this case you have to open the streaming video instead of a single image frame. for each frame you have to find the faces, you can use the OpenCV haar-cascade or the [deepgaze face detection class](https://github.com/mpatacchiola/deepgaze/blob/master/deepgaze/face_detection.py). When you isolated the faces you can give the subframe as input to the CNN head pose estimator class like in [here](https://github.com/mpatacchiola/deepgaze/tree/master/examples/ex_cnn_headp_pose_estimation_images). Moreover, in [this example](https://github.com/mpatacchiola/deepgaze/blob/master/examples/ex_pnp_head_pose_estimation_video.py) I isolated the faces in a video stream and then I sent the sub-frames to a PnP head pose estimator.

Good luck

**Comment by ZhangQihang** [comment]
Hi

I wonder if “ for each frame you have to find the faces” means if some frames contains no face，the program will fail to run？

**Comment by mpatacchiola** [comment]
Hi ZhangQihang

No the script does not fail to run. When you do not find any face you do not need to pass the face subframe to the Convolutional Network. Meaning that for that particular frame you do not call any head estimation.

Massimiliano
