### ISSUE TITLE
Notebooks

### ISSUE THREAD

**Issue by Deamoner** [mpatacchiola/deepgaze#99]
Hey I got notebooks working. What notebooks do you guys want for examples I'll contribute those?

**Comment by mpatacchiola** [comment]
Hi @Deamoner if you want to contribute you are welcome. Be sure you are using [branch 2.0](https://github.com/mpatacchiola/deepgaze/tree/2.0) in the repository, since this will be soon used as the main branch and the current master branch will be deprecated.

Any step-by-step notebook which covers some of the scripts in the [example folder](https://github.com/mpatacchiola/deepgaze/tree/2.0/examples) is more than welcome. Double check the [Notebooks folder](https://github.com/mpatacchiola/deepgaze/tree/2.0/examples/Notebooks) to avoid any duplicate.

You can send a push request if you have stable code, we will review it and then add it to the library if everything checks out.

**Comment by Deamoner** [comment]
I'll put together a few.

**Comment by mpatacchiola** [comment]
All right!
